# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXv700-XIKtzzo1gscBQVY06l7yWAlJO
"""

!pip install transformers datasets torch seqeval -q

import torch
import numpy as np
from transformers import AutoTokenizer, AutoModelForTokenClassification
from torch.utils.data import DataLoader, TensorDataset
from torch.optim import AdamW
from seqeval.metrics import classification_report, f1_score

import warnings
warnings.filterwarnings('ignore')

print("✅ Setup complete!")

# POS tags
pos_tags = ['NNP', 'VBZ', 'DT', 'NN', 'VB', 'JJ', 'RB', 'PRP', 'IN', 'CC']
num_labels = len(pos_tags)

# Sentences
sentences = [
    ["John", "loves", "Python"],
    ["The", "cat", "sleeps"],
    ["She", "runs", "fast"],
    ["Python", "is", "great"],
    ["I", "like", "ice", "cream"],
]

# Labels
labels_data = [
    [0, 1, 0],
    [2, 3, 1],
    [7, 1, 6],
    [0, 1, 5],
    [7, 1, 3, 3],
]

print("✅ Dataset ready")

model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    ignore_mismatched_sizes=True
)

device = torch.device("cpu")
model.to(device)

print("✅ Model loaded")

def prepare_data(sentences, labels, max_len=15):
    input_ids_list = []
    attention_masks_list = []
    labels_list = []

    for sent, labs in zip(sentences, labels):
        encoding = tokenizer(
            sent,
            is_split_into_words=True,
            truncation=True,
            padding='max_length',
            max_length=max_len,
            return_tensors='pt'
        )

        word_ids = encoding.word_ids()
        aligned_labels = []
        prev_id = None

        for word_id in word_ids:
            if word_id is None:
                aligned_labels.append(-100)
            elif word_id != prev_id:
                aligned_labels.append(labs[word_id] if word_id < len(labs) else -100)
            else:
                aligned_labels.append(-100)
            prev_id = word_id

        input_ids_list.append(encoding['input_ids'].squeeze())
        attention_masks_list.append(encoding['attention_mask'].squeeze())
        labels_list.append(torch.tensor(aligned_labels))

    return (
        torch.stack(input_ids_list),
        torch.stack(attention_masks_list),
        torch.stack(labels_list)
    )

input_ids, masks, labels = prepare_data(sentences, labels_data)

dataset = TensorDataset(input_ids, masks, labels)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

print("✅ Data prepared")

optimizer = AdamW(model.parameters(), lr=2e-5)

model.train()

epochs = 20

for epoch in range(epochs):
    total_loss = 0

    for batch in dataloader:
        input_ids, masks, labels = [b.to(device) for b in batch]

        optimizer.zero_grad()

        outputs = model(
            input_ids=input_ids,
            attention_mask=masks,
            labels=labels
        )

        loss = outputs.loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}: Loss = {total_loss/len(dataloader):.4f}")

print("✅ Training complete!")

def predict(sentence):
    words = sentence.split()

    inputs = tokenizer(words, is_split_into_words=True, return_tensors="pt")

    model.eval()
    with torch.no_grad():
        outputs = model(**inputs)
        preds = torch.argmax(outputs.logits, dim=2)[0]

    word_ids = inputs.word_ids()

    results = []
    last_id = None

    for i, wid in enumerate(word_ids):
        if wid is not None and wid != last_id:
            tag = pos_tags[preds[i].item()]
            results.append((words[wid], tag))
        last_id = wid

    return results


print("Predictions")

for sentence in ["John loves Python", "She runs fast"]:
    print("\nSentence:", sentence)
    print(predict(sentence))

# Dummy evaluation example (since small dataset)

true_labels = [["NNP", "VBZ", "NNP"]]
pred_labels = [["NNP", "VBZ", "NNP"]]

print("F1 Score:", f1_score(true_labels, pred_labels))
print("\nClassification Report:")
print(classification_report(true_labels, pred_labels))

print("""
POS Tagging vs Chunking

POS Tagging:
- Labels each word
- Example: John → NNP

Chunking:
- Groups words into phrases
- Example: [John] NP

POS → Easy
Chunking → Medium
""")

